"""Unit tests for ode.ModelDerivatives class.

Tests verify that Python implementation matches reference values
generated from the C code (csrc/models.c _HS functions).
"""

import csv
from pathlib import Path
import numpy as np
import pytest

from fkptjax.ode import ModelDerivatives, ODESolver, growth_factor
from fkptjax.snapshot import load_snapshot

# Test parameters matching the C reference generator
OM = 0.3
OL = 0.7
FR0 = 1e-3
BETA2 = 1.0 / 6.0
NHS = 1
SCREENING = 1.0
OMEGABD = 0.0

# Tolerance for floating point comparisons
RTOL = 1e-14
ATOL = 1e-15


@pytest.fixture(scope="module")
def derivs():
    """Create ModelDerivatives instance with test parameters."""
    return ModelDerivatives(
        om=OM,
        ol=OL,
        fR0=FR0,
        beta2=BETA2,
        nHS=NHS,
        screening=SCREENING,
        omegaBD=OMEGABD,
    )


@pytest.fixture(scope="module")
def reference_data():
    """Load reference values from CSV file generated by C code."""
    csv_path = Path(__file__).parent / "ode_reference_values.csv"
    if not csv_path.exists():
        pytest.skip(f"Reference data file not found: {csv_path}")

    data = {}
    with open(csv_path, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            # Skip comments
            if not row or row[0].startswith('#'):
                continue

            func_name = row[0]
            # Parse parameters (handle empty strings as None)
            params = []
            for val in row[1:9]:  # eta, k, p, x, Dpk, Dpp, D2f, D2mf
                params.append(float(val) if val else None)
            result = float(row[9])

            if func_name not in data:
                data[func_name] = []
            data[func_name].append((*params, result))

    return data


@pytest.fixture(scope="module")
def snapshot():
    return load_snapshot()


class TestBasicFunctions:
    """Test basic cosmological functions (eta only)."""

    def test_OmM(self, derivs, reference_data):
        """Test matter density parameter OmM."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['OmM']:
            result = derivs.OmM(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"OmM({eta}) failed")

    def test_H(self, derivs, reference_data):
        """Test Hubble parameter H."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['H']:
            result = derivs.H(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"H({eta}) failed")

    def test_f1(self, derivs, reference_data):
        """Test growth rate f1."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['f1']:
            result = derivs.f1(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"f1({eta}) failed")

    def test_A0(self, derivs, reference_data):
        """Test growth parameter A0."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['A0']:
            result = derivs.A0(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"A0({eta}) failed")

    def test_mass(self, derivs, reference_data):
        """Test scalar mass."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['mass']:
            result = derivs.mass(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"mass({eta}) failed")

    def test_M1(self, derivs, reference_data):
        """Test M1 mass function."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['M1']:
            result = derivs.M1(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"M1({eta}) failed")

    def test_M2(self, derivs, reference_data):
        """Test M2 mass function."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['M2']:
            result = derivs.M2(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"M2({eta}) failed")

    def test_M3(self, derivs, reference_data):
        """Test M3 mass function."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['M3']:
            result = derivs.M3(eta)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"M3({eta}) failed")


class TestWavenumberFunctions:
    """Test functions depending on wavenumbers."""

    def test_mu(self, derivs, reference_data):
        """Test modified gravity parameter mu."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['mu']:
            result = derivs.mu(eta, k)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"mu({eta}, {k}) failed")

    def test_PiF(self, derivs, reference_data):
        """Test PiF function."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['PiF']:
            result = derivs.PiF(eta, k)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"PiF({eta}, {k}) failed")

    def test_kpp(self, derivs, reference_data):
        """Test kpp wavenumber combination."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['kpp']:
            result = derivs.kpp(x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"kpp({x}, {k}, {p}) failed")


class TestSecondOrderHelpers:
    """Test second-order helper functions."""

    def test_KFL2(self, derivs, reference_data):
        """Test KFL2 kernel."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['KFL2']:
            result = derivs.KFL2(eta, x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"KFL2({eta}, {x}, {k}, {p}) failed")

    def test_JFL(self, derivs, reference_data):
        """Test JFL function."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['JFL']:
            result = derivs.JFL(eta, x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"JFL({eta}, {x}, {k}, {p}) failed")

    def test_S2a(self, derivs, reference_data):
        """Test S2a source term."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S2a']:
            result = derivs.S2a(eta, x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S2a({eta}, {x}, {k}, {p}) failed")

    def test_S2b(self, derivs, reference_data):
        """Test S2b source term."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S2b']:
            result = derivs.S2b(eta, x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S2b({eta}, {x}, {k}, {p}) failed")

    def test_S2FL(self, derivs, reference_data):
        """Test S2FL fifth-force source."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S2FL']:
            result = derivs.S2FL(eta, x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S2FL({eta}, {x}, {k}, {p}) failed")

    def test_S2dI(self, derivs, reference_data):
        """Test S2dI source term."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S2dI']:
            result = derivs.S2dI(eta, x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S2dI({eta}, {x}, {k}, {p}) failed")

    def test_SD2(self, derivs, reference_data):
        """Test SD2 combined second-order source."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['SD2']:
            result = derivs.SD2(eta, x, k, p)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"SD2({eta}, {x}, {k}, {p}) failed")


class TestThirdOrderFunctions:
    """Test third-order source functions."""

    def test_D2phiplus(self, derivs, reference_data):
        """Test D2phiplus function."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['D2phiplus']:
            result = derivs.D2phiplus(eta, x, k, p, Dpk, Dpp, D2f)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"D2phiplus({eta}, {x}, {k}, {p}, {Dpk}, {Dpp}, {D2f}) failed")

    def test_D2phiminus(self, derivs, reference_data):
        """Test D2phiminus function."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['D2phiminus']:
            result = derivs.D2phiminus(eta, x, k, p, Dpk, Dpp, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"D2phiminus({eta}, {x}, {k}, {p}, {Dpk}, {Dpp}, {D2mf}) failed")

    def test_K3dI(self, derivs, reference_data):
        """Test K3dI kernel."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['K3dI']:
            result = derivs.K3dI(eta, x, k, p, Dpk, Dpp, D2f, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"K3dI({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3IIplus(self, derivs, reference_data):
        """Test S3IIplus source term."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3IIplus']:
            result = derivs.S3IIplus(eta, x, k, p, Dpk, Dpp, D2f)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3IIplus({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3IIminus(self, derivs, reference_data):
        """Test S3IIminus source term."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3IIminus']:
            result = derivs.S3IIminus(eta, x, k, p, Dpk, Dpp, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3IIminus({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3II(self, derivs, reference_data):
        """Test S3II combined source."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3II']:
            result = derivs.S3II(eta, x, k, p, Dpk, Dpp, D2f, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3II({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3FLplus(self, derivs, reference_data):
        """Test S3FLplus fifth-force source."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3FLplus']:
            result = derivs.S3FLplus(eta, x, k, p, Dpk, Dpp, D2f)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3FLplus({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3FLminus(self, derivs, reference_data):
        """Test S3FLminus fifth-force source."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3FLminus']:
            result = derivs.S3FLminus(eta, x, k, p, Dpk, Dpp, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3FLminus({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3FL(self, derivs, reference_data):
        """Test S3FL combined fifth-force source."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3FL']:
            result = derivs.S3FL(eta, x, k, p, Dpk, Dpp, D2f, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3FL({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3I(self, derivs, reference_data):
        """Test S3I source term."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3I']:
            result = derivs.S3I(eta, x, k, p, Dpk, Dpp, D2f, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3I({eta}, {x}, {k}, {p}, ...) failed")

    def test_S3dI(self, derivs, reference_data):
        """Test S3dI source term."""
        for eta, k, p, x, Dpk, Dpp, D2f, D2mf, expected in reference_data['S3dI']:
            result = derivs.S3dI(eta, x, k, p, Dpk, Dpp, D2f, D2mf)
            np.testing.assert_allclose(result, expected, rtol=RTOL, atol=ATOL,
                                       err_msg=f"S3dI({eta}, {x}, {k}, {p}, ...) failed")


class TestGrowthIntegration:
    """Test integration of growth ODEs."""

    def test_first_order_growth(self, snapshot):

        k_in = snapshot.arrays.k_in
        f_in = snapshot.arrays.f_in
        derivs = ModelDerivatives(om=OM, ol=OL, fR0=1e-6)
        for method in ('RKQS', 'scipy_ivp'):
            solver = ODESolver(zout=0.5, method=method)
            f_out = growth_factor(k_in, derivs, solver)
            np.testing.assert_allclose(
                f_out, f_in, rtol=2e-4, atol=2e-4,
                err_msg=f"f(k) integration failed for method {method}")
